"""empty message

Revision ID: 1adbf9a47b86
Revises: 6af065118400
Create Date: 2024-03-04 12:49:48.943216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adbf9a47b86'
down_revision = '6af065118400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('platforms_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system_name')
    )
    op.create_table('game_genres_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games_table.id'], name=op.f('fk_game_genres_table_game_id_games_table')),
    sa.ForeignKeyConstraint(['genre_id'], ['genres_table.id'], name=op.f('fk_game_genres_table_genre_id_genres_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_platforms_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games_table.id'], name=op.f('fk_game_platforms_table_game_id_games_table')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms_table.id'], name=op.f('fk_game_platforms_table_platform_id_platforms_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_platforms_table')
    op.drop_table('game_genres_table')
    op.drop_table('platforms_table')
    op.drop_table('genres_table')
    # ### end Alembic commands ###
