"""empty message

Revision ID: fd8cbccc7b62
Revises: 1adbf9a47b86
Create Date: 2024-03-05 13:31:07.504939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd8cbccc7b62'
down_revision = '1adbf9a47b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bestseller', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games_table', schema=None) as batch_op:
        batch_op.drop_column('bestseller')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
